When picklestep=20, some features have all NaN values but need to know which samples and which features.

Graph sizes are weird: (smaller size, less connectivity)
    
Data(x=[414, 31], y=[2], contact_edge_index=[2, 92], lineage_edge_index=[2, 236])

Data(x=[519, 31], y=[2], contact_edge_index=[2, 374], lineage_edge_index=[2, 272])

Data(x=[643, 31], y=[2], contact_edge_index=[2, 80], lineage_edge_index=[2, 325])

Data(x=[795, 31], y=[2], contact_edge_index=[2, 172], lineage_edge_index=[2, 479])

Data(x=[455, 31], y=[2], contact_edge_index=[2, 140], lineage_edge_index=[2, 217])

Data(x=[1233, 31], y=[2], contact_edge_index=[2, 1034], lineage_edge_index=[2, 830])

Data(x=[460, 31], y=[2], contact_edge_index=[2, 60], lineage_edge_index=[2, 233])

Data(x=[375, 31], y=[2], contact_edge_index=[2, 372], lineage_edge_index=[2, 197])

Data(x=[1013, 31], y=[2], contact_edge_index=[2, 582], lineage_edge_index=[2, 650])

Data(x=[371, 31], y=[2], contact_edge_index=[2, 62], lineage_edge_index=[2, 214])

Data(x=[706, 31], y=[2], contact_edge_index=[2, 408], lineage_edge_index=[2, 394])

Data(x=[641, 31], y=[2], contact_edge_index=[2, 340], lineage_edge_index=[2, 337])

Data(x=[582, 31], y=[2], contact_edge_index=[2, 30], lineage_edge_index=[2, 327])

Data(x=[502, 31], y=[2], contact_edge_index=[2, 268], lineage_edge_index=[2, 256])

Data(x=[437, 31], y=[2], contact_edge_index=[2, 430], lineage_edge_index=[2, 250])

Data(x=[548, 31], y=[2], contact_edge_index=[2, 1354], lineage_edge_index=[2, 267])

Data(x=[380, 31], y=[2], contact_edge_index=[2, 90], lineage_edge_index=[2, 166])

Data(x=[536, 31], y=[2], contact_edge_index=[2, 490], lineage_edge_index=[2, 304])

Data(x=[1002, 31], y=[2], contact_edge_index=[2, 116], lineage_edge_index=[2, 559])

etc...


ln(gamma mean):  3.5376507732087004

ln(gamma std):  1.9790876149410934

ln(alpha mean):  1.1723906061388658

ln(alpha std):  1.9858896670392767

ln(gamma min):  0.005614210784468326

ln(gamma max):  6.902720907774605

ln(alpha min):  -2.2991908599260302

ln(alpha max):  4.599327550988798

In [ ]:
import pickle as pk
import torch
import numpy as np
import os
import pandas as pd

In [45]:
g_path = "s6_0313_01.pkl"

with open(g_path, "rb") as f:
    data = pk.load(f)

print(type(data))
print(len(data))
print(type(list(data.values())[0]))

<class 'dict'>
997
<class 'torch_geometric.data.data.Data'>


In [46]:
g = list(data.values())[0]

print(g)
print(g.x.shape)
print(g.y)

Data(x=[414, 31], y=[2], contact_edge_index=[2, 92], lineage_edge_index=[2, 236])
torch.Size([414, 31])
tensor([0.8837, 0.4402])


In [47]:
bad_graphs = []

for i, g in enumerate(data.values()):

    if hasattr(g, "x"):
        if torch.isnan(g.x).any() or torch.isinf(g.x).any():
            print(f"Graph {i} has NaN/Inf in x")
            bad_graphs.append(i)

    if hasattr(g, "y"):
        if torch.isnan(g.y).any() or torch.isinf(g.y).any():
            print(f"Graph {i} has NaN/Inf in y")
            print(g.y)
            bad_graphs.append(i)

    if hasattr(g, "edge_attr") and g.edge_attr is not None:
        if torch.isnan(g.edge_attr).any() or torch.isinf(g.edge_attr).any():
            print(f"Graph {i} has NaN/Inf in edge_attr")
            bad_graphs.append(i)

print("Bad graphs:", bad_graphs)

Graph 80 has NaN/Inf in x
Graph 922 has NaN/Inf in x
Bad graphs: [80, 922]


In [48]:
g = list(data.values())[922]

In [49]:
idx = torch.nonzero(torch.isnan(g.x) | torch.isinf(g.x))
print(idx[:20])
print(g.x[idx[:,0], idx[:,1]])

tensor([[ 0,  9],
        [ 0, 10],
        [ 1,  9],
        [ 1, 10],
        [ 2,  9],
        [ 2, 10],
        [ 3,  9],
        [ 3, 10],
        [ 4,  9],
        [ 4, 10],
        [ 5,  9],
        [ 5, 10],
        [ 6,  9],
        [ 6, 10],
        [ 7,  9],
        [ 7, 10],
        [ 8,  9],
        [ 8, 10],
        [ 9,  9],
        [ 9, 10]])
tensor([nan, nan, nan,  ..., nan, nan, nan])


In [51]:
print(g.y)
print(torch.isnan(g.y))

tensor([-1.2402,  1.4482])
tensor([False, False])


In [52]:
ln_gamma = -1.2402*1.979+3.538
np.exp(ln_gamma)

2.9554301290161225

In [53]:
ln_alpha = 1.4482*1.986+1.172
np.exp(ln_alpha)

57.289949102412905

In [54]:
for i, g in enumerate(data.values()):
    print(
        i,
        g.x.min().item(),
        g.x.max().item(),
        g.x.abs().max().item()
    )
    break

0 -7.042996406555176 6.109872817993164 7.042996406555176


In [55]:
g = list(data.values())[80]

In [56]:
idx = torch.nonzero(torch.isnan(g.x) | torch.isinf(g.x))
print(idx[:20])
print(g.x[idx[:,0], idx[:,1]])

tensor([[ 0,  9],
        [ 0, 10],
        [ 1,  9],
        [ 1, 10],
        [ 2,  9],
        [ 2, 10],
        [ 3,  9],
        [ 3, 10],
        [ 4,  9],
        [ 4, 10],
        [ 5,  9],
        [ 5, 10],
        [ 6,  9],
        [ 6, 10],
        [ 7,  9],
        [ 7, 10],
        [ 8,  9],
        [ 8, 10],
        [ 9,  9],
        [ 9, 10]])
tensor([nan, nan, nan,  ..., nan, nan, nan])


In [58]:
print(g.y)
print(torch.isnan(g.y))

tensor([ 0.3453, -1.6317])
tensor([False, False])


In [59]:
ln_gamma = 0.3453*1.979+3.538
np.exp(ln_gamma)

68.12530295367894

In [60]:
ln_alpha = -1.6317*1.986+1.172
np.exp(ln_alpha)

0.1263681003208021

In [61]:
for i, g in enumerate(data.values()):
    print(
        i,
        g.x.min().item(),
        g.x.max().item(),
        g.x.abs().max().item()
    )
    break

0 -7.042996406555176 6.109872817993164 7.042996406555176


In [22]:
path = "D:/Projects/GNN Research/Data Files/_sim_tr_csv_data_gnn/2026-03-13/"
[os.listdir(f) for f in [path+f for f in os.listdir(path)]]

[['gamma=551.09594_reg_param=9.91473_iter=0'],
 ['gamma=215.1234_reg_param=0.2628_iter=1'],
 ['gamma=292.79141_reg_param=0.95084_iter=2'],
 ['gamma=15.03897_reg_param=13.36843_iter=3'],
 ['gamma=36.35732_reg_param=31.86485_iter=4'],
 ['gamma=13.56152_reg_param=53.71274_iter=5'],
 ['gamma=30.18722_reg_param=2.14284_iter=6'],
 ['gamma=6.95809_reg_param=0.16177_iter=7'],
 ['gamma=303.48455_reg_param=30.86254_iter=8'],
 ['gamma=1.60325_reg_param=25.84842_iter=9'],
 ['gamma=819.54178_reg_param=1.62194_iter=10'],
 ['gamma=878.33567_reg_param=27.90283_iter=11'],
 ['gamma=15.69332_reg_param=3.88403_iter=12'],
 ['gamma=598.05568_reg_param=14.83259_iter=13'],
 ['gamma=19.242_reg_param=13.05599_iter=14'],
 ['gamma=8.19855_reg_param=1.52852_iter=15'],
 ['gamma=17.47134_reg_param=14.47787_iter=16'],
 ['gamma=508.41761_reg_param=28.59381_iter=17'],
 ['gamma=1.77059_reg_param=11.35259_iter=18'],
 ['gamma=7.72342_reg_param=1.7371_iter=19'],
 ['gamma=10.86577_reg_param=17.69271_iter=20'],
 ['gamma=1.49

In [62]:
def smart_cast(val):
    try:
        return float(val)
    except ValueError:
        if val == 'True':
            return float(1)
        elif val == 'False':
            return float(0)
        elif val == 'TRUE':
            return float(1)
        elif val == 'FALSE':
            return float(0)
        elif val == 'YFP':
            return float(1)
        else:
            return val  # keep as string if not a number
        
include_columns = ['ImageNumber', #
                       'ObjectNumber', #
                       'id', #
                       'parent_id', #
                       'AreaShape_Area', #
                       'AreaShape_MajorAxisLength', #
                       'AreaShape_Orientation', #
                       'cellAge', #
                       'LifeHistory', #
                       'TrajectoryX', #
                       'TrajectoryY', #
                       'Direction_of_Motion', #
                       'Motion_Alignment_Angle', #
                       'Source_Neighbor_Avg_TrajectoryX', #
                       'Source_Neighbor_Avg_TrajectoryY', #
                       'Division_TimeStep', #
                       'Daughter_Mother_Length_Ratio', #
                       'Total_Daughter_Mother_Length_Ratio', #
                       'Max_Daughter_Mother_Length_Ratio', #
                       'Daughter_Avg_TrajectoryX', #
                       'Daughter_Avg_TrajectoryY', #
                       'Neighbor_Difference_Count', #
                       'Neighbor_Shared_Count', #
                       'Average_Length', #
                       'Velocity', #
                       'Instant_Velocity', #
                       'Average_Instant_Velocity', #
                       'Elongation_Rate', #
                       'Instant_Elongation_Rate', #
                       'startVol', #
                       'targetVol', #
                       'Prev_MajorAxisLength', #
                       'Bacterium_Movement', #
                       'dir_1', 'dir_2', #
                       ]

In [64]:
# issue csv
p = "666.csv"
node_features_df = pd.read_csv(p)
for col in node_features_df.columns:
    node_features_df[col] = node_features_df[col].map(smart_cast)
    
node_features_df['dir'] = node_features_df['dir'].apply(eval).apply(lambda x: tuple(map(float, x)))
vec_df = pd.DataFrame(node_features_df['dir'].tolist(), columns=['dir_1', 'dir_2'])
node_features_df = pd.concat([node_features_df.drop(columns=['dir']), vec_df], axis=1)

# print(len(include_columns))
node_features_df = node_features_df[include_columns]
node_features_df = node_features_df.fillna(node_features_df.mean(numeric_only=True))
#print(node_features_df.head())

node_index_df = node_features_df.iloc[:, :4]
node_features_df = node_features_df.iloc[:, 4:]

# Standard normalization
#df_normalized = node_features_df.copy()
#binary_columns = ["divideFlag", "Unexpected_End", "Unexpected_Beginning"]
#for col in node_features_df.columns:
#    if col not in binary_columns:
#        df_normalized[col] = (node_features_df[col] - mean_dict[col])/std_dict[col]

#node_features_df = df_normalized


all_nan_cols = node_features_df.columns[node_features_df.isna().all()]

print("Columns that are ALL NaN:")
print(all_nan_cols)

Columns that are ALL NaN:
Index(['Source_Neighbor_Avg_TrajectoryX', 'Source_Neighbor_Avg_TrajectoryY'], dtype='object')


In [66]:
node_features_df[['Source_Neighbor_Avg_TrajectoryX', 'Source_Neighbor_Avg_TrajectoryY']]

,Source_Neighbor_Avg_TrajectoryX,Source_Neighbor_Avg_TrajectoryY
0,NaN,NaN
1,NaN,NaN
2,NaN,NaN
3,NaN,NaN
4,NaN,NaN
...,...,...
529,NaN,NaN
530,NaN,NaN
531,NaN,NaN
532,NaN,NaN


In [43]:
# normal csv
p = "777.csv"
node_features_df = pd.read_csv(p)
for col in node_features_df.columns:
    node_features_df[col] = node_features_df[col].map(smart_cast)
    
node_features_df['dir'] = node_features_df['dir'].apply(eval).apply(lambda x: tuple(map(float, x)))
vec_df = pd.DataFrame(node_features_df['dir'].tolist(), columns=['dir_1', 'dir_2'])
node_features_df = pd.concat([node_features_df.drop(columns=['dir']), vec_df], axis=1)

# print(len(include_columns))
node_features_df = node_features_df[include_columns]
node_features_df = node_features_df.fillna(node_features_df.mean(numeric_only=True))
#print(node_features_df.head())

node_index_df = node_features_df.iloc[:, :4]
node_features_df = node_features_df.iloc[:, 4:]

# Standard normalization
#df_normalized = node_features_df.copy()
#binary_columns = ["divideFlag", "Unexpected_End", "Unexpected_Beginning"]
#for col in node_features_df.columns:
#    if col not in binary_columns:
#        df_normalized[col] = (node_features_df[col] - mean_dict[col])/std_dict[col]

#node_features_df = df_normalized


all_nan_cols = node_features_df.columns[node_features_df.isna().all()]

print("Columns that are ALL NaN:")
print(all_nan_cols)

Columns that are ALL NaN:
Index([], dtype='object')


Now we see the issue is. Try to set picklestep = 2 instead. Maybe 1 is better.